name: Send Email
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  send_email:
    runs-on: ubuntu-latest
 
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Novo Push no Repositório"
          body: "Foi realizado um push no repositório. Verifique o código."
          to: ${{ secrets.EMAIL_USERNAME2 }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true